title: Card Gaming Society
description: >-
  The Card Gaming Society at the University of Sheffield meets every Sunday to
  play new and exciting card games. Run by students, for students
baseurl: "/"
url: "https://cardgaming.union.shef.ac.uk"
twitter_username: CardGamesSoc
facebook_username: SheffieldCardGamesSociety

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-autoprefixer

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Dockerfile
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/img/banner"
    values:
      banner: true
  - scope:
      path: "assets/img/icons"
    values:
      icon: true
  - scope:
      path: "assets/games"
    values:
      game: true

sass:
  sass_dir: _sass
  style: compressed

header_pages:
 - index.markdown
 - about.markdown
 - games.markdown
